services:
  mysql:
    image: mysql:8.0
    container_name: mysql-inventory-management
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Krasi148!
      MYSQL_DATABASE: inventory_management
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: